-- ----------------------------------------------------
-- Luma Focus Cafe - Supabase Database Schema
-- ----------------------------------------------------

-- 1. Create Profiles Table (extends Supabase Auth Users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    username TEXT,
    coins INTEGER DEFAULT 100, -- starts with 100 coins to buy a first item
    high_score INTEGER DEFAULT 0, -- total minutes focused
    active_theme TEXT DEFAULT 'default'
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-only access to profiles" 
    ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Allow users to update their own profile" 
    ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2. Create Unlocked Items Table (stores purchased assets)
CREATE TABLE IF NOT EXISTS public.unlocked_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    item_id TEXT NOT NULL,
    unlocked_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(user_id, item_id)
);

ALTER TABLE public.unlocked_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to view their own unlocked items" 
    ON public.unlocked_items FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow users to insert their own unlocked items" 
    ON public.unlocked_items FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 3. Create Focus Sessions Table (stores log history)
CREATE TABLE IF NOT EXISTS public.focus_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    duration INTEGER NOT NULL, -- duration in minutes
    completed BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.focus_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to view their own focus sessions" 
    ON public.focus_sessions FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow users to log their own focus sessions" 
    ON public.focus_sessions FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 4. Trigger to automatically create a profile when a user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, username, coins, high_score, active_theme)
  VALUES (new.id, split_part(new.email, '@', 1), 100, 0, 'default');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
